import { PaddleOCR } from '@paddleocr/paddleocr-js';
const $=id=>document.getElementById(id); const now=()=>new Date().toISOString(); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':'&quot;',"'":'&#39;'}[c]));
let engine=null,summary=null,ready=false,photos=[],selected=0,rotation=0,analysis=null,baseRows=[];
function msg(t,k=''){ $('msg').textContent=t; $('msg').className='msg '+k }
function threads(){return self.crossOriginIsolated?Math.max(1,Math.min(4,(navigator.hardwareConcurrency||2)-1)):1}
function applyTheme(pref){localStorage.setItem('fs-theme',pref);let x=pref;if(pref==='system')x=matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';document.documentElement.dataset.theme=x;$('themeSelect').value=pref}
$('themeBtn').onclick=()=>applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');$('themeSelect').onchange=e=>applyTheme(e.target.value);applyTheme(localStorage.getItem('fs-theme')||'system');
document.querySelectorAll('.navbtn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.navbtn').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+b.dataset.view));if(b.dataset.view==='history')renderHistory()});
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.panel').forEach(v=>v.classList.toggle('active',v.id===b.dataset.tab))});
async function initOCR(){if(ready)return; $('ocrBadge').textContent='OCR local: carregando…';msg('A carregar PaddleOCR local…');try{engine=await PaddleOCR.create({initialize:false,worker:false,textDetectionModelName:'PP-OCRv5_mobile_det',textRecognitionModelName:'PP-OCRv5_mobile_rec',ortOptions:{backend:'wasm',wasmPaths:'https://cdn.jsdelivr.net/npm/onnxruntime-web/dist/',numThreads:threads(),simd:true}});summary=await engine.initialize();ready=true;$('ocrBadge').textContent='OCR local: operacional';$('ocrBadge').style.color='var(--green)';$('analyzeBtn').disabled=!photos.length;msg('OCR local operacional. Pronto para analisar.','ok')}catch(e){console.error(e);$('ocrBadge').textContent='OCR local: falhou';msg('Falha ao inicializar OCR: '+(e.message||e),'err')}}
$('initBtn').onclick=initOCR;
function addFiles(list){const v=[...list].filter(f=>/^image\/(jpeg|png|webp)$/.test(f.type));if(!v.length)return msg('Use JPG, PNG ou WebP.','err');photos.push(...v.map(file=>({file,url:URL.createObjectURL(file)})));selected=Math.max(0,photos.length-v.length);renderPhotos();$('analyzeBtn').disabled=!ready||!photos.length;msg(`${v.length} foto(s) adicionada(s).`)}
$('addBtn').onclick=()=>$('files').click();$('files').onchange=e=>addFiles(e.target.files);['dragenter','dragover'].forEach(ev=>$('drop').addEventListener(ev,e=>{e.preventDefault();$('drop').classList.add('drag')}));$('drop').addEventListener('dragleave',()=> $('drop').classList.remove('drag'));$('drop').addEventListener('drop',e=>{e.preventDefault();$('drop').classList.remove('drag');addFiles(e.dataTransfer.files)});
function renderPhotos(){ $('fileCount').textContent=`${photos.length} foto${photos.length===1?'':'s'}`;$('drop').style.display=photos.length?'none':'flex';$('viewer').style.display=photos.length?'flex':'none';if(photos.length)$('mainImg').src=photos[selected].url;$('thumbs').innerHTML=photos.map((p,i)=>`<img class="thumb ${i===selected?'active':''}" data-i="${i}" src="${p.url}" title="${esc(p.file.name)}">`).join('');document.querySelectorAll('.thumb').forEach(t=>t.onclick=()=>{selected=+t.dataset.i;rotation=0;renderPhotos();applyTransform()})}
function applyTransform(){const z=+$('zoom').value;$('zoomLabel').textContent=z+'%';$('mainImg').style.transform=`scale(${z/100}) rotate(${rotation}deg)`}$('zoom').oninput=applyTransform;$('rotL').onclick=()=>{rotation-=90;applyTransform()};$('rotR').onclick=()=>{rotation+=90;applyTransform()};
function boxOf(it){const p=it.poly||it.box||[];const pts=Array.isArray(p[0])?p:[];if(!pts.length)return{left:0,right:0,top:0,bottom:0,cx:0,cy:0,w:0,h:0};const xs=pts.map(q=>Number(q[0])||0),ys=pts.map(q=>Number(q[1])||0),left=Math.min(...xs),right=Math.max(...xs),top=Math.min(...ys),bottom=Math.max(...ys);return{left,right,top,bottom,cx:(left+right)/2,cy:(top+bottom)/2,w:right-left,h:bottom-top}}
function median(a){const v=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!v.length)return 0;const m=Math.floor(v.length/2);return v.length%2?v[m]:(v[m-1]+v[m])/2}
function reconstruct(blocks){const pages=new Map();for(const b of blocks){if(!pages.has(b.page))pages.set(b.page,[]);pages.get(b.page).push(b)}const rows=[];for(const [page,arr] of pages){const mh=Math.max(7,median(arr.map(x=>x.box.h))||18);const groups=[];for(const it of arr.slice().sort((a,b)=>a.box.cy-b.box.cy||a.box.left-b.box.left)){let best=null,dist=1e9;for(const g of groups){const gy=median(g.map(x=>x.box.cy));const gh=Math.max(6,median(g.map(x=>x.box.h))||mh);const d=Math.abs(it.box.cy-gy),lim=Math.max(5,Math.min(22,Math.max(gh,it.box.h)*.55,mh*.55));if(d<=lim&&d<dist){best=g;dist=d}}if(best)best.push(it);else groups.push([it])}groups.sort((a,b)=>median(a.map(x=>x.box.cy))-median(b.map(x=>x.box.cy)));groups.forEach((g,i)=>{g.sort((a,b)=>a.box.left-b.box.left);rows.push({id:`P${page}-R${String(i+1).padStart(3,'0')}`,page,source_ids:g.map(x=>x.id),text:g.map(x=>x.text).join(' ').replace(/\s+/g,' ').trim(),cells:g.map(x=>({id:x.id,text:x.text,score:x.score,left:x.box.left,right:x.box.right,top:x.box.top,bottom:x.box.bottom,cx:x.box.cx,cy:x.box.cy}))})})}return rows}
function parse(rows){const rejected=[],items=[];const header=/\b(COD|PRODUTOS?|DESCRI[CÇ][AÃ]O|QTD|QUANTIDADE|UNIDS?|PRE[CÇ]O|IMPORT[AÂ]NCIA|TOTAL|IVA)\b/i;const section=/\b(TROCAS?|PROMO[CÇ][AÃ]O|DESCONTO)\b/i;const footer=/\b(NIF|CLIENTE|FORNECEDOR|MORADA|ATCUD|IBAN|PAGAMENTO|BASE TRIBUT|VALOR IVA|TOTAL A PAGAR|TOTAL DOCUMENTO)\b/i;for(const r of rows){const t=r.text.trim();if(!t)continue;if(header.test(t)&&r.cells.length<=8){rejected.push({source:r.id,text:t,reason:'Cabeçalho/estrutura da tabela'});continue}if(section.test(t)){rejected.push({source:r.id,text:t,reason:'Secção especial; não criada como artigo'});continue}if(footer.test(t)){rejected.push({source:r.id,text:t,reason:'Metadado/fiscal/rodapé'});continue}const nums=r.cells.filter(c=>/^[+-]?\d{1,8}(?:[.,]\d{1,4})?%?$/.test(c.text.replace(/\s/g,''))).sort((a,b)=>a.left-b.left);const textCells=r.cells.filter(c=>!nums.includes(c));const desc=textCells.map(c=>c.text).join(' ').trim();const refCell=textCells.find(c=>/^(?=.*\d)[A-Z0-9._\/-]{3,20}$/i.test(c.text));let qty=null,price=null,total=null;if(nums.length>=3){qty=nums.at(-3).text;price=nums.at(-2).text;total=nums.at(-1).text}else if(nums.length===2){qty=nums[0].text;price=nums[1].text}else if(nums.length===1){price=nums[0].text}const evidence=(refCell?2:0)+(desc.length>=4?1:0)+(nums.length>=2?2:nums.length);if(evidence<3){rejected.push({source:r.id,text:t,reason:'Estrutura insuficiente para artigo'});continue}const score=Math.min(99,45+(refCell?20:0)+(nums.length>=2?20:10)+(desc.length>=8?10:0)+Math.round((r.cells.reduce((s,c)=>s+(Number(c.score)||0),0)/Math.max(1,r.cells.length))*5));items.push({source:r.id,source_ids:r.source_ids,reference:refCell?.text||null,description:desc||t,quantity:qty,unit_price:price,total,confidence:score})}return{items,rejected}}
async function analyze(){if(!ready)await initOCR();if(!ready||!photos.length)return;const started=performance.now(),blocks=[],pages=[],raw=[];$('analyzeBtn').disabled=true;msg('A executar OCR local…');try{for(let p=0;p<photos.length;p++){const t=performance.now();const [r]=await engine.predict(photos[p].file,{textDetThresh:.3,textDetBoxThresh:.55,textDetUnclipRatio:1.5,textRecScoreThresh:.10});const src=r.items||[];const normalized=src.map((x,i)=>{const b=boxOf(x);return{id:`P${p+1}-B${String(i+1).padStart(3,'0')}`,page:p+1,text:String(x.text||''),score:Number(x.score??x.confidence??0),poly:x.poly||x.box||null,box:b}});blocks.push(...normalized);pages.push({page:p+1,file:{name:photos[p].file.name,type:photos[p].file.type,size:photos[p].file.size},run_ms:Math.round(performance.now()-t),block_count:normalized.length});raw.push(`=== FOTO ${p+1}: ${photos[p].file.name} ===\n`+normalized.map(x=>`${x.id}\t${x.text}`).join('\n'))}const rows=reconstruct(blocks),parsed=parse(rows);analysis={app:{name:'Fatura → Sage 50',version:'0.6.7',report_schema:'1.0'},generated_at:now(),pipeline:'local_paddleocr_direct_v067',engine:{package:'@paddleocr/paddleocr-js@0.4.2',det_model:'PP-OCRv5_mobile_det',rec_model:'PP-OCRv5_mobile_rec',backend:'wasm',summary},timings:{total_ms:Math.round(performance.now()-started)},pages,raw_ocr_text:raw.join('\n\n'),ocr_blocks:blocks.map(x=>({id:x.id,page:x.page,text:x.text,score:x.score,poly:x.poly,bounds:x.box})),reconstructed_rows:rows,articles:parsed.items,rejected:parsed.rejected,notes:['Este relatório não contém resultado esperado nem comparação automática.','A comparação deve ser feita externamente com a imagem original.']};renderAnalysis();saveHistory(analysis);msg(`Concluído: ${parsed.items.length} candidatos, ${parsed.rejected.length} rejeitados.`,'ok')}catch(e){console.error(e);msg('Falha no OCR/análise: '+(e.message||e),'err');$('diagBox').textContent=e.stack||String(e)}finally{$('analyzeBtn').disabled=!photos.length}}
$('analyzeBtn').onclick=analyze;
function renderAnalysis(){const a=analysis;$('stBlocks').textContent=a.ocr_blocks.length;$('stRows').textContent=a.reconstructed_rows.length;$('stItems').textContent=a.articles.length;$('stReject').textContent=a.rejected.length;$('ocrBox').textContent=a.raw_ocr_text||'(sem texto)';$('rowsBox').textContent=a.reconstructed_rows.map(r=>`${r.id}\t${r.text}`).join('\n')||'(sem linhas reconstruídas)';$('itemsBody').innerHTML=a.articles.length?a.articles.map(x=>`<tr><td>${esc(x.source)}</td><td>${esc(x.reference??'—')}</td><td>${esc(x.description)}</td><td>${esc(x.quantity??'—')}</td><td>${esc(x.unit_price??'—')}</td><td>${esc(x.total??'—')}</td><td><span class="status ${x.confidence>=80?'good':'warn'}">${x.confidence}%</span></td></tr>`).join(''):'<tr><td colspan="7"><div class="empty">Nenhum candidato.</div></td></tr>';$('rejBody').innerHTML=a.rejected.length?a.rejected.map(x=>`<tr><td>${esc(x.source)}</td><td>${esc(x.text)}</td><td>${esc(x.reason)}</td></tr>`).join(''):'<tr><td colspan="3"><div class="empty">Nenhuma linha rejeitada.</div></td></tr>';$('diagBox').textContent=JSON.stringify({app:a.app,pipeline:a.pipeline,engine:a.engine,timings:a.timings,pages:a.pages,counts:{ocr_blocks:a.ocr_blocks.length,reconstructed_rows:a.reconstructed_rows.length,articles:a.articles.length,rejected:a.rejected.length}},null,2);$('reportBtn').disabled=false;$('csvBtn').disabled=false}
function safe(s){return String(s||'fatura').replace(/[^a-z0-9._-]+/gi,'_').slice(0,70)}function dl(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function reportText(a){return [`FATURA → SAGE 50 · RELATÓRIO DE TESTE`,`Versão: ${a.app.version}`,`Gerado: ${a.generated_at}`,`Pipeline: ${a.pipeline}`,`Tempo total: ${a.timings.total_ms} ms`,``,`== PÁGINAS ==`,...a.pages.map(p=>`Foto ${p.page}: ${p.file.name} | ${p.file.size} bytes | ${p.block_count} blocos | ${p.run_ms} ms`),``,`== OCR BRUTO ==`,a.raw_ocr_text,``,`== LINHAS RECONSTRUÍDAS ==`,...a.reconstructed_rows.map(r=>`${r.id} | ${r.text}`),``,`== ARTIGOS ==`,...a.articles.map((x,i)=>`${i+1}. ${x.source} | ref=${x.reference??''} | desc=${x.description} | qtd=${x.quantity??''} | preço=${x.unit_price??''} | total=${x.total??''} | conf=${x.confidence}%`),``,`== REJEITADOS ==`,...a.rejected.map(x=>`${x.source} | ${x.reason} | ${x.text}`),``,`NOTA: a app não contém resultado esperado e não faz comparação automática.`].join('\n')}
$('reportBtn').onclick=()=>{if(!analysis)return;const base=`fatura_sage_relatorio_${new Date().toISOString().replace(/[:.]/g,'-')}`;dl(base+'.json',JSON.stringify(analysis,null,2),'application/json');setTimeout(()=>dl(base+'.txt',reportText(analysis),'text/plain;charset=utf-8'),250)};
$('csvBtn').onclick=()=>{if(!analysis)return;const q=v=>'"'+String(v??'').replaceAll('"','""')+'"';const rows=[['source','reference','description','quantity','unit_price','total','confidence'],...analysis.articles.map(x=>[x.source,x.reference,x.description,x.quantity,x.unit_price,x.total,x.confidence])];dl('fatura_sage_auditoria.csv','\ufeff'+rows.map(r=>r.map(q).join(';')).join('\r\n'),'text/csv;charset=utf-8')};
function saveHistory(a){try{const h=JSON.parse(localStorage.getItem('fs-history')||'[]');h.unshift({at:a.generated_at,files:a.pages.map(p=>p.file.name),counts:{blocks:a.ocr_blocks.length,rows:a.reconstructed_rows.length,items:a.articles.length,rejected:a.rejected.length},report:a});localStorage.setItem('fs-history',JSON.stringify(h.slice(0,10)))}catch{}}
function renderHistory(){let h=[];try{h=JSON.parse(localStorage.getItem('fs-history')||'[]')}catch{};$('historyList').innerHTML=h.length?h.map((x,i)=>`<div class="notice"><b>${new Date(x.at).toLocaleString()}</b><br><span class="small">${esc(x.files.join(', '))}</span><br><span class="small muted">${x.counts.items} artigos · ${x.counts.rejected} rejeitados</span> <button class="btn histReport" data-i="${i}" style="margin-left:8px">Baixar relatório</button></div>`).join(''):'<div class="empty">Nenhuma análise guardada.</div>';document.querySelectorAll('.histReport').forEach(b=>b.onclick=()=>{const x=h[+b.dataset.i];dl(`relatorio_${safe(x.at)}.json`,JSON.stringify(x.report,null,2),'application/json')})}
$('newBtn').onclick=()=>{photos.forEach(p=>URL.revokeObjectURL(p.url));photos=[];selected=0;rotation=0;analysis=null;$('files').value='';renderPhotos();$('analyzeBtn').disabled=true;$('reportBtn').disabled=true;$('csvBtn').disabled=true;$('stBlocks').textContent=$('stRows').textContent=$('stItems').textContent=$('stReject').textContent='0';$('ocrBox').textContent='O OCR bruto aparecerá aqui.';$('rowsBox').textContent='As linhas reconstruídas aparecerão aqui.';$('itemsBody').innerHTML='<tr><td colspan="7"><div class="empty">Nenhum candidato ainda.</div></td></tr>';$('rejBody').innerHTML='<tr><td colspan="3"><div class="empty">Nenhuma linha rejeitada.</div></td></tr>';msg('Pronto para a próxima fatura.')};
$('baseBtn').onclick=()=>$('baseFile').click();$('baseFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;const t=await f.text();baseRows=t.split(/\r?\n/).filter(Boolean);$('baseCount').textContent=`${baseRows.length} linhas`;$('basePreview').textContent=baseRows.slice(0,60).join('\n')||'Nenhuma base carregada.'};
renderPhotos();
