import { PaddleOCR } from '@paddleocr/paddleocr-js';
const $=id=>document.getElementById(id);
const now=()=>new Date().toISOString();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':'&quot;',"'":'&#39;'}[c]));
let engine=null,summary=null,ready=false,photos=[],selected=0,rotation=0,analysis=null,baseRows=[];
function msg(t,k=''){ $('msg').textContent=t; $('msg').className='msg '+k }
function threads(){return self.crossOriginIsolated?Math.max(1,Math.min(4,(navigator.hardwareConcurrency||2)-1)):1}
function applyTheme(pref){localStorage.setItem('fs-theme',pref);let x=pref;if(pref==='system')x=matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light';document.documentElement.dataset.theme=x;$('themeSelect').value=pref}
$('themeBtn').onclick=()=>applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');$('themeSelect').onchange=e=>applyTheme(e.target.value);applyTheme(localStorage.getItem('fs-theme')||'system');
document.querySelectorAll('.navbtn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.navbtn').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+b.dataset.view));if(b.dataset.view==='history')renderHistory()});
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.panel').forEach(v=>v.classList.toggle('active',v.id===b.dataset.tab))});
async function initOCR(){if(ready)return;$('ocrBadge').textContent='OCR local: carregando…';msg('A carregar PaddleOCR local…');try{engine=await PaddleOCR.create({initialize:false,worker:false,textDetectionModelName:'PP-OCRv5_mobile_det',textRecognitionModelName:'PP-OCRv5_mobile_rec',ortOptions:{backend:'wasm',wasmPaths:'https://cdn.jsdelivr.net/npm/onnxruntime-web/dist/',numThreads:threads(),simd:true}});summary=await engine.initialize();ready=true;$('ocrBadge').textContent='OCR local: operacional';$('ocrBadge').style.color='var(--green)';$('analyzeBtn').disabled=!photos.length;msg('OCR local operacional. Pronto para analisar.','ok')}catch(e){console.error(e);$('ocrBadge').textContent='OCR local: falhou';msg('Falha ao inicializar OCR: '+(e.message||e),'err')}}
$('initBtn').onclick=initOCR;
function addFiles(list){const v=[...list].filter(f=>/^image\/(jpeg|png|webp)$/.test(f.type));if(!v.length)return msg('Use JPG, PNG ou WebP.','err');photos.push(...v.map(file=>({file,url:URL.createObjectURL(file)})));selected=Math.max(0,photos.length-v.length);renderPhotos();$('analyzeBtn').disabled=!ready||!photos.length;msg(`${v.length} foto(s) adicionada(s).`)}
$('addBtn').onclick=()=>$('files').click();$('files').onchange=e=>addFiles(e.target.files);['dragenter','dragover'].forEach(ev=>$('drop').addEventListener(ev,e=>{e.preventDefault();$('drop').classList.add('drag')}));$('drop').addEventListener('dragleave',()=>$('drop').classList.remove('drag'));$('drop').addEventListener('drop',e=>{e.preventDefault();$('drop').classList.remove('drag');addFiles(e.dataTransfer.files)});
function renderPhotos(){$('fileCount').textContent=`${photos.length} foto${photos.length===1?'':'s'}`;$('drop').style.display=photos.length?'none':'flex';$('viewer').style.display=photos.length?'flex':'none';if(photos.length)$('mainImg').src=photos[selected].url;$('thumbs').innerHTML=photos.map((p,i)=>`<img class="thumb ${i===selected?'active':''}" data-i="${i}" src="${p.url}" title="${esc(p.file.name)}">`).join('');document.querySelectorAll('.thumb').forEach(t=>t.onclick=()=>{selected=+t.dataset.i;rotation=0;renderPhotos();applyTransform()})}
function applyTransform(){const z=+$('zoom').value;$('zoomLabel').textContent=z+'%';$('mainImg').style.transform=`scale(${z/100}) rotate(${rotation}deg)`}$('zoom').oninput=applyTransform;$('rotL').onclick=()=>{rotation-=90;applyTransform()};$('rotR').onclick=()=>{rotation+=90;applyTransform()};
function boxOf(it){const p=it.poly||it.box||[];const pts=Array.isArray(p[0])?p:[];if(!pts.length)return{left:0,right:0,top:0,bottom:0,cx:0,cy:0,w:0,h:0};const xs=pts.map(q=>Number(q[0])||0),ys=pts.map(q=>Number(q[1])||0),left=Math.min(...xs),right=Math.max(...xs),top=Math.min(...ys),bottom=Math.max(...ys);return{left,right,top,bottom,cx:(left+right)/2,cy:(top+bottom)/2,w:right-left,h:bottom-top}}
function median(a){const v=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!v.length)return 0;const m=Math.floor(v.length/2);return v.length%2?v[m]:(v[m-1]+v[m])/2}
function norm(s){return String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/\s+/g,' ').trim()}
function compact(s){return norm(s).replace(/[^A-Z0-9%]/g,'')}
function isNumText(s){return /^[+-]?\d{1,8}(?:[.,]\d{1,4})?%?$/.test(String(s??'').replace(/\s/g,''))}
function asNumber(v){if(v==null)return null;const n=Number(String(v).replace(/\s/g,'').replace(',','.').replace('%',''));return Number.isFinite(n)?n:null}
function reconstruct(blocks){const pages=new Map();for(const b of blocks){if(!pages.has(b.page))pages.set(b.page,[]);pages.get(b.page).push(b)}const rows=[];for(const [page,arr] of pages){const mh=Math.max(7,median(arr.map(x=>x.box.h))||18),groups=[];for(const it of arr.slice().sort((a,b)=>a.box.cy-b.box.cy||a.box.left-b.box.left)){let best=null,dist=1e9;for(const g of groups){const gy=median(g.map(x=>x.box.cy)),gh=Math.max(6,median(g.map(x=>x.box.h))||mh),d=Math.abs(it.box.cy-gy),lim=Math.max(5,Math.min(24,Math.max(gh,it.box.h)*.58,mh*.62));if(d<=lim&&d<dist){best=g;dist=d}}if(best)best.push(it);else groups.push([it])}groups.sort((a,b)=>median(a.map(x=>x.box.cy))-median(b.map(x=>x.box.cy)));groups.forEach((g,i)=>{g.sort((a,b)=>a.box.left-b.box.left);rows.push({id:`P${page}-R${String(i+1).padStart(3,'0')}`,page,cy:median(g.map(x=>x.box.cy)),source_ids:g.map(x=>x.id),text:g.map(x=>x.text).join(' ').replace(/\s+/g,' ').trim(),cells:g.map(x=>({id:x.id,text:x.text,score:x.score,left:x.box.left,right:x.box.right,top:x.box.top,bottom:x.box.bottom,cx:x.box.cx,cy:x.box.cy}))})})}return rows}
function aliasKind(text){const x=compact(text);if(/^(COD|CODIGO|REF|REFERENCIA)$/.test(x))return'ref';if(x.includes('PRODUT')||x.includes('DESCR')||x==='ARTIGO'||/^DES[UCR]/.test(x))return'desc';if(x.includes('IVA')||x==='TVA'||x==='TWA')return'vat';if(x.includes('QUANT')||x.includes('QTD')||x.includes('UNID')||x==='DUANT'||x==='OUANT')return'qty';if(x.includes('PRECO')||x==='PVP'||x.includes('UNITARIO')||x.includes('PUNIT')||x==='PRUNIT')return'price';if(x==='TOTAL'||x.includes('IMPORT')||x==='VALOR')return'total';return null}
function detectHeaderFromBlocks(blocks){const candidates=blocks.map(b=>({...b,kind:aliasKind(b.text)})).filter(b=>b.kind);let best=null;for(const c of candidates){const band=candidates.filter(x=>Math.abs(x.box.cy-c.box.cy)<=55);const kinds=[...new Set(band.map(x=>x.kind))];const hasTwo=['qty','price','vat','total'].filter(k=>kinds.includes(k)).length;const hasStd=['ref','desc','qty','price','total'].filter(k=>kinds.includes(k)).length;const score=Math.max(hasTwo+(kinds.includes('desc')?1:0),hasStd);if(score>=4&&(!best||score>best.score)){const anchors={};for(const k of kinds){const same=band.filter(x=>x.kind===k);anchors[k]=median(same.map(x=>x.box.cx))}best={score,band,kinds,anchors,mode:kinds.includes('ref')&&kinds.includes('desc')?'horizontal':'two_line',top:Math.min(...band.map(x=>x.box.top)),bottom:Math.max(...band.map(x=>x.box.bottom))}}return best}
function splitReferenceAndDescriptionText(text){const s=String(text||'').trim();let m=s.match(/^\s*(\d{4,12})(.*)$/);if(!m)m=s.match(/^\s*((?=[A-Z0-9._\/-]{3,20})(?=[A-Z0-9._\/-]*\d)[A-Z0-9._\/-]+)(.*)$/i);return m?{reference:m[1],description:m[2].trim()||null}:{reference:null,description:s||null}}
function looksFooterText(t){const n=norm(t);return /\b(ITENS?|ITEMS?|TOTAL\s*[: ]|BASE\s*IMP|BASE\s*TRIB|VALOR\s*IVA|ATCUD|SALDO|PAGAMENTO|MULTIBANCO|IBAN|PROCESSADO|CERTIFICADO)\b/.test(n)}
function scoreItem(blocks,vals,mathCheck,base=66){const avg=blocks.reduce((s,c)=>s+(Number(c.score)||0),0)/Math.max(1,blocks.length);let c=base+(vals.qty?5:0)+(vals.price?5:0)+(vals.total?5:0)+(vals.vat?2:0)+(mathCheck===true?9:0)+Math.round(avg*5);return Math.min(99,c)}
function parseHorizontalBlocks(blocks,header){const rejected=[],items=[],used=new Set(),body=blocks.filter(b=>b.box.top>header.bottom-5).sort((a,b)=>a.box.cy-b.box.cy);const refs=body.filter(b=>{const s=splitReferenceAndDescriptionText(b.text);return s.reference&&s.description});for(const d of refs){const split=splitReferenceAndDescriptionText(d.text);if(/TROCAS?|DESCONTO|PROMO/i.test(d.text))continue;const near=body.filter(b=>!used.has(b.id)&&isNumText(b.text)&&Math.abs(b.box.cy-d.box.cy)<=35);const vals={vat:null,qty:null,price:null,total:null},sources={reference:d.id,description:[d.id]};for(const b of near){let best=null,dist=1e9;for(const k of ['vat','qty','price','total']){if(!Number.isFinite(header.anchors[k]))continue;const dd=Math.abs(b.box.cx-header.anchors[k]);if(dd<dist){best=k;dist=dd}}if(best&&dist<125&&vals[best]==null){vals[best]=b.text;sources[best]=b.id}}
if(['qty','price','total'].filter(k=>vals[k]!=null).length<2)continue;const q=asNumber(vals.qty),p=asNumber(vals.price),tot=asNumber(vals.total),math=q!=null&&p!=null&&tot!=null?Math.abs(q*p-tot)<=Math.max(.04,Math.abs(tot)*.012):null;items.push({source:d.id,source_ids:[d.id,...Object.values(sources).flat().filter(x=>x&&x!==d.id)],reference:split.reference,description:split.description,vat:vals.vat,quantity:vals.qty,unit_price:vals.price,total:vals.total,confidence:scoreItem([d,...near],vals,math,70),section:'MAIN',row_type:'product',layout_mode:'horizontal',math_check:math,field_sources:sources});used.add(d.id);Object.values(sources).flat().forEach(x=>used.add(x))}
for(const b of body.filter(x=>!used.has(x.id)))rejected.push({source:b.id,text:b.text,reason:'Bloco fora de artigo principal',section:'REVIEW'});return{items,rejected,debug:{header_blocks:header.band.map(x=>x.id)}}}
function parseTiltedBlocks(blocks,header){const rejected=[],items=[],used=new Set();const body=blocks.filter(b=>b.box.top>header.bottom-8).sort((a,b)=>a.box.cy-b.box.cy);let footerY=Infinity;for(const b of body){if(looksFooterText(b.text)&&b.box.cy>header.bottom+180)footerY=Math.min(footerY,b.box.top)}const table=body.filter(b=>b.box.top<footerY);const descBlocks=table.filter(b=>!isNumText(b.text)&&!aliasKind(b.text)&&/[A-Za-zÀ-ÿ]{3}/.test(b.text)&&!looksFooterText(b.text)&&!/(FATURA|CLIENTE|DATA|NIF|CONTRIB|ATCUD)/i.test(b.text));const numeric=table.filter(b=>isNumText(b.text));const centers={qty:header.anchors.qty,price:header.anchors.price,vat:header.anchors.vat,total:header.anchors.total};for(const d of descBlocks){if(used.has(d.id))continue;const descParts=[d];for(const e of descBlocks){if(e.id===d.id||used.has(e.id))continue;const dy=Math.abs(e.box.cy-d.box.cy),gap=e.box.left-d.box.right;if(dy<=18&&gap>-25&&gap<120)descParts.push(e)}descParts.sort((a,b)=>a.box.left-b.box.left);const desc=descParts.map(x=>x.text).join(' ').replace(/\s+/g,' ').trim();if(desc.length<4)continue;const cand=numeric.filter(n=>!used.has(n.id)&&Math.abs(n.box.cy-d.box.cy)<=48);const byKey={};for(const k of ['qty','price','vat','total']){if(!Number.isFinite(centers[k]))continue;const pool=cand.filter(n=>Math.abs(n.box.cx-centers[k])<95).sort((a,b)=>Math.abs(a.box.cx-centers[k])-Math.abs(b.box.cx-centers[k])||Math.abs(a.box.cy-d.box.cy)-Math.abs(b.box.cy-d.box.cy));byKey[k]=pool.slice(0,5)}let best=null;const qs=byKey.qty||[],ps=byKey.price||[],ts=byKey.total||[];for(const q of qs)for(const p of ps)for(const t of ts){if(new Set([q.id,p.id,t.id]).size<3)continue;const qn=asNumber(q.text),pn=asNumber(p.text),tn=asNumber(t.text);if(qn==null||pn==null||tn==null)continue;const err=Math.abs(qn*pn-tn),tol=Math.max(.06,Math.abs(tn)*.018);const ypen=(Math.abs(q.box.cy-d.box.cy)+Math.abs(p.box.cy-d.box.cy)+Math.abs(t.box.cy-d.box.cy))/150;const score=err/tol+ypen;if(err<=tol*2&&(!best||score<best.score))best={q,p,t,score,err,tol}}
if(!best)continue;let vat=null;if(byKey.vat?.length){vat=byKey.vat.find(v=>v.id!==best.q.id&&v.id!==best.p.id&&v.id!==best.t.id)||null}const vals={qty:best.q.text,price:best.p.text,total:best.t.text,vat:vat?.text??null},sources={description:descParts.map(x=>x.id),qty:best.q.id,price:best.p.id,total:best.t.id,vat:vat?.id??null};const math=best.err<=best.tol;const all=[...descParts,best.q,best.p,best.t,...(vat?[vat]:[])];const refSplit=splitReferenceAndDescriptionText(desc);items.push({source:descParts.map(x=>x.id).join(' + '),source_ids:all.map(x=>x.id),reference:refSplit.reference,description:refSplit.reference?(refSplit.description||desc):desc,vat:vals.vat,quantity:vals.qty,unit_price:vals.price,total:vals.total,confidence:scoreItem(all,vals,math,68),section:'MAIN',row_type:'product',layout_mode:'two_line_tilted',math_check:math,field_sources:sources});all.forEach(x=>used.add(x.id))}
for(const b of body.filter(x=>!used.has(x.id)))rejected.push({source:b.id,text:b.text,reason:b.box.top>=footerY?'Rodapé/totais':'Bloco não associado a artigo com validação matemática',section:b.box.top>=footerY?'POST_TABLE':'REVIEW'});return{items,rejected,debug:{header_blocks:header.band.map(x=>x.id),footer_y:Number.isFinite(footerY)?footerY:null,description_candidates:descBlocks.length,numeric_candidates:numeric.length}}}
function parseAll(blocks){const items=[],rejected=[],pageMeta=[];const pages=[...new Set(blocks.map(b=>b.page))];for(const page of pages){const bs=blocks.filter(b=>b.page===page);const h=detectHeaderFromBlocks(bs);if(!h){pageMeta.push({page,header:null,anchors:null,layout_mode:'unknown',debug:{reason:'header_not_found'}});bs.forEach(b=>rejected.push({source:b.id,text:b.text,reason:'Cabeçalho não identificado',section:'PREAMBLE'}));continue}const parsed=h.mode==='horizontal'?parseHorizontalBlocks(bs,h):parseTiltedBlocks(bs,h);items.push(...parsed.items);rejected.push(...parsed.rejected);pageMeta.push({page,header:h.band.map(x=>x.id),anchors:h.anchors,layout_mode:h.mode==='horizontal'?'horizontal':'two_line_tilted',debug:parsed.debug})}return{items,rejected,page_meta:pageMeta}}
async function analyze(){if(!ready)await initOCR();if(!ready||!photos.length)return;const started=performance.now(),blocks=[],pages=[],raw=[];$('analyzeBtn').disabled=true;msg('A executar OCR local…');try{for(let p=0;p<photos.length;p++){const t=performance.now();const [r]=await engine.predict(photos[p].file,{textDetThresh:.3,textDetBoxThresh:.55,textDetUnclipRatio:1.5,textRecScoreThresh:.10});const src=r.items||[];const normalized=src.map((x,i)=>{const b=boxOf(x);return{id:`P${p+1}-B${String(i+1).padStart(3,'0')}`,page:p+1,text:String(x.text||''),score:Number(x.score??x.confidence??0),poly:x.poly||x.box||null,box:b}});blocks.push(...normalized);pages.push({page:p+1,file:{name:photos[p].file.name,type:photos[p].file.type,size:photos[p].file.size},run_ms:Math.round(performance.now()-t),block_count:normalized.length});raw.push(`=== FOTO ${p+1}: ${photos[p].file.name} ===\n`+normalized.map(x=>`${x.id}\t${x.text}`).join('\n'))}const rows=reconstruct(blocks),parsed=parseAll(blocks);analysis={app:{name:'Fatura → Sage 50',version:'0.6.8.1',report_schema:'1.3'},generated_at:now(),pipeline:'local_paddleocr_direct_v0681_block_geometry',engine:{package:'@paddleocr/paddleocr-js@0.4.2',det_model:'PP-OCRv5_mobile_det',rec_model:'PP-OCRv5_mobile_rec',backend:'wasm',summary},parser:{name:'multilayout_v4_block_geometry',modes:['horizontal','two_line_tilted'],fuzzy_header:true,block_geometry:true,math_validation:true,page_meta:parsed.page_meta},timings:{total_ms:Math.round(performance.now()-started)},pages,raw_ocr_text:raw.join('\n\n'),ocr_blocks:blocks.map(x=>({id:x.id,page:x.page,text:x.text,score:x.score,poly:x.poly,bounds:x.box})),reconstructed_rows:rows,articles:parsed.items,rejected:parsed.rejected,notes:['Comparação continua fora da app.','0.6.8.1 aceita variantes OCR do cabeçalho como DUANT/QUANT e TVA/IVA.','No layout inclinado os artigos são associados diretamente por blocos e validados por quantidade × preço ≈ total.']};renderAnalysis();saveHistory(analysis);const modes=[...new Set(parsed.page_meta.map(x=>x.layout_mode))].join(', ');msg(`Concluído: ${parsed.items.length} artigos · layout: ${modes||'não identificado'}.`,'ok')}catch(e){console.error(e);msg('Falha no OCR/análise: '+(e.message||e),'err');$('diagBox').textContent=e.stack||String(e)}finally{$('analyzeBtn').disabled=!photos.length}}
$('analyzeBtn').onclick=analyze;
function renderAnalysis(){const a=analysis;$('stBlocks').textContent=a.ocr_blocks.length;$('stRows').textContent=a.reconstructed_rows.length;$('stItems').textContent=a.articles.length;$('stReject').textContent=a.rejected.length;$('ocrBox').textContent=a.raw_ocr_text||'(sem texto)';$('rowsBox').textContent=a.reconstructed_rows.map(r=>`${r.id}\t${r.text}`).join('\n')||'(sem linhas reconstruídas)';$('itemsBody').innerHTML=a.articles.length?a.articles.map(x=>`<tr><td>${esc(x.source)}</td><td>${esc(x.reference??'—')}</td><td>${esc(x.description)}</td><td>${esc(x.quantity??'—')}</td><td>${esc(x.unit_price??'—')}</td><td>${esc(x.total??'—')}</td><td><span class="status ${x.confidence>=80?'good':'warn'}">${x.confidence}%</span></td></tr>`).join(''):'<tr><td colspan="7"><div class="empty">Nenhum candidato.</div></td></tr>';$('rejBody').innerHTML=a.rejected.length?a.rejected.map(x=>`<tr><td>${esc(x.source)}</td><td>${esc(x.text)}</td><td>${esc(x.reason)}${x.section?` · ${esc(x.section)}`:''}</td></tr>`).join(''):'<tr><td colspan="3"><div class="empty">Nenhuma linha rejeitada.</div></td></tr>';$('diagBox').textContent=JSON.stringify({app:a.app,pipeline:a.pipeline,parser:a.parser,engine:a.engine,timings:a.timings,pages:a.pages,counts:{ocr_blocks:a.ocr_blocks.length,reconstructed_rows:a.reconstructed_rows.length,articles:a.articles.length,rejected:a.rejected.length}},null,2);$('reportBtn').disabled=false;$('csvBtn').disabled=false}
function safe(s){return String(s||'fatura').replace(/[^a-z0-9._-]+/gi,'_').slice(0,70)}function dl(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function reportText(a){return [`FATURA → SAGE 50 · RELATÓRIO DE TESTE`,`Versão: ${a.app.version}`,`Gerado: ${a.generated_at}`,`Pipeline: ${a.pipeline}`,`Parser: ${a.parser?.name||''}`,`Layouts: ${(a.parser?.page_meta||[]).map(x=>`P${x.page}=${x.layout_mode}`).join(', ')}`,`Tempo total: ${a.timings.total_ms} ms`,``,`== PÁGINAS ==`,...a.pages.map(p=>`Foto ${p.page}: ${p.file.name} | ${p.file.size} bytes | ${p.block_count} blocos | ${p.run_ms} ms`),``,`== OCR BRUTO ==`,a.raw_ocr_text,``,`== LINHAS RECONSTRUÍDAS ==`,...a.reconstructed_rows.map(r=>`${r.id} | ${r.text}`),``,`== ARTIGOS ==`,...a.articles.map((x,i)=>`${i+1}. ${x.source} | layout=${x.layout_mode} | ref=${x.reference??''} | desc=${x.description} | iva=${x.vat??''} | qtd=${x.quantity??''} | preço=${x.unit_price??''} | total=${x.total??''} | conf=${x.confidence}% | math=${x.math_check}`),``,`== REJEITADOS ==`,...a.rejected.map(x=>`${x.source} | ${x.section||''} | ${x.reason} | ${x.text}`),``,`NOTA: a app não contém resultado esperado e não faz comparação automática.`].join('\n')}
$('reportBtn').onclick=()=>{if(!analysis)return;const base=`fatura_sage_relatorio_${new Date().toISOString().replace(/[:.]/g,'-')}`;dl(base+'.json',JSON.stringify(analysis,null,2),'application/json');setTimeout(()=>dl(base+'.txt',reportText(analysis),'text/plain;charset=utf-8'),250)};
$('csvBtn').onclick=()=>{if(!analysis)return;const q=v=>'"'+String(v??'').replaceAll('"','""')+'"';const rows=[['source','layout_mode','reference','description','vat','quantity','unit_price','total','confidence','math_check'],...analysis.articles.map(x=>[x.source,x.layout_mode,x.reference,x.description,x.vat,x.quantity,x.unit_price,x.total,x.confidence,x.math_check])];dl('fatura_sage_auditoria.csv','\ufeff'+rows.map(r=>r.map(q).join(';')).join('\r\n'),'text/csv;charset=utf-8')};
function saveHistory(a){try{const h=JSON.parse(localStorage.getItem('fs-history')||'[]');h.unshift({at:a.generated_at,files:a.pages.map(p=>p.file.name),counts:{blocks:a.ocr_blocks.length,rows:a.reconstructed_rows.length,items:a.articles.length,rejected:a.rejected.length},report:a});localStorage.setItem('fs-history',JSON.stringify(h.slice(0,10)))}catch{}}
function renderHistory(){let h=[];try{h=JSON.parse(localStorage.getItem('fs-history')||'[]')}catch{};$('historyList').innerHTML=h.length?h.map((x,i)=>`<div class="notice"><b>${new Date(x.at).toLocaleString()}</b><br><span class="small">${esc(x.files.join(', '))}</span><br><span class="small muted">${x.counts.items} artigos · ${x.counts.rejected} rejeitados</span> <button class="btn histReport" data-i="${i}" style="margin-left:8px">Baixar relatório</button></div>`).join(''):'<div class="empty">Nenhuma análise guardada.</div>';document.querySelectorAll('.histReport').forEach(b=>b.onclick=()=>{const x=h[+b.dataset.i];dl(`relatorio_${safe(x.at)}.json`,JSON.stringify(x.report,null,2),'application/json')})}
$('newBtn').onclick=()=>{photos.forEach(p=>URL.revokeObjectURL(p.url));photos=[];selected=0;rotation=0;analysis=null;$('files').value='';renderPhotos();$('analyzeBtn').disabled=true;$('reportBtn').disabled=true;$('csvBtn').disabled=true;$('stBlocks').textContent=$('stRows').textContent=$('stItems').textContent=$('stReject').textContent='0';$('ocrBox').textContent='O OCR bruto aparecerá aqui.';$('rowsBox').textContent='As linhas reconstruídas aparecerão aqui.';$('itemsBody').innerHTML='<tr><td colspan="7"><div class="empty">Nenhum candidato ainda.</div></td></tr>';$('rejBody').innerHTML='<tr><td colspan="3"><div class="empty">Nenhuma linha rejeitada.</div></td></tr>';msg('Pronto para a próxima fatura.')};
$('baseBtn').onclick=()=>$('baseFile').click();$('baseFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;const t=await f.text();baseRows=t.split(/\r?\n/).filter(Boolean);$('baseCount').textContent=`${baseRows.length} linhas`;$('basePreview').textContent=baseRows.slice(0,60).join('\n')||'Nenhuma base carregada.'};
renderPhotos();